accounts/urls.py
from django.conf.urls import re_path, include
from django.urls import path
from accounts import views

app_name = 'accounts'

urlpatterns = [
    re_path(r'delete/(?P<pk>\d+)/', views.user_delete, name ='delete'),
]

home/urls.py
from django.conf.urls import url
from home import views

urlpatterns = [
	url(r'^$', views.index, name ='index.html'),
]

visitMaker/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.views.generic import RedirectView
from accounts.views import (login_view, register_view, logout_view, list_users)
from home.views import(contact_view)
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include ('home.urls')) ,
    url(r'^request_reservation/', include('requestReserv.urls')),
    url(r'^reservation_home/', include('reservHome.urls', 'reservations')),
   # url(r'^contact_us/', include('contactUs.urls')),
    url(r'^register/', register_view, name='register'),
    url(r'^contact_us', contact_view , name = 'contactUs.html'),
    url(r'^manage/', list_users, name ='Users/manage.html'),
    url(r'^accounts/', include('accounts.urls', 'accounts')),
    url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^report_generation/', include('Reports.urls')),
    url(r'^$', RedirectView.as_view(url='/home', permanent = True)),
]

home/views.py
from django.shortcuts import render
# Create your views here.

def index(request):
	return render (request, 'index.html',)

def contact_view(request):
  return render(request, 'contactUs.html',)

home/templates/Users/list_users.html
{% load static %}
<html>
	{% include "univheader.html" %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/display_entries.css' %}">
	<!-- jQuery -->
	<script type="text/javascript" charset="utf8" src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.8.2.min.js"></script>
	<!-- DataTables -->
	<script type="text/javascript" charset="utf8" src="http://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/jquery.dataTables.min.js"></script>
	<body class="background">
		<h2>Existing Users</h2>
		<table id="display_entries" class="display_entries">
			<thead>
			<tr>
				<th>User</th>
				<th>Delete</th>
			</tr>
			</thead>
			<tbody>
				{% for entry in entries %}
				<tr>
					<td>{{entry.username}}</td>
					<td><a href="{% url 'accounts:delete' pk=entry.pk %}"><span class="glyphicon glyphicon-trash"></span></a></td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
		<script>
		$(function(){
			$("#display_entries").dataTable();
		})
		</script>
		<p style="font-size: 20px; text-align: right;"> <br> Click <a href= "/home/">here</a> to return to the home page. </p>
	</body>
</html>

home/templates/Users/loginPage.html
{% load static %}
<html>
	{% include "univheader.html" %}
	{% block content %}
	<body class="background">
		<div class='col-sm-6 col-sm-offset-3'>
			<h1>
				{{title}}
			</h1>

			<form method='POST' action='' enctype='multipart/form-data'>
				{% csrf_token %}
				{{form.as_p}}
				<input type="submit" class='btn btn-default' value='{{title}}' />
			</form>
		</div>
	</body>
	{% endblock content %}
</html>