home/urls.py
from django.conf.urls import url
from home import views

urlpatterns = [
	url(r'^$', views.index, name ='index.html'),
]

requestReserv/urls.py
from django.conf.urls import re_path, include
from requestReserv import views

app_name = 'requests'

urlpatterns = [
  re_path(r'^$', views.request_new, name ='Requests/requestReserv.html'),
  re_path(r'list/', views.list, name ='list'),
  re_path(r'delete/(?P<pk>\d+)/', views.delete, name ='delete'),
  re_path(r'confirm_request/(?P<pk>\d+)/', views.request_conf, name ='confirmRequest'),
]

reservHome/urls.py
from django.conf.urls import re_path, include
from django.urls import path
from reservHome import views

app_name = 'reservations'

urlpatterns = [
	path('add_reservation/', views.reserv_new, name ='add_reservation'),
	# (route, view, kwargs=NONE, name=NONE)
    re_path(r'confirm_reservation/(?P<pk>\d+)/', views.reserv_conf, name ='confirm_reservation'),
    re_path(r'send_email/(?P<pk>\d+)/', views.send_email, name ='send_email'),
    re_path(r'edit/(?P<pk>\d+)/', views.reserv_edit, name ='edit'),
    re_path(r'delete/(?P<pk>\d+)/', views.reserv_delete, name ='delete'),
    re_path(r'day_list/(?P<date>[0-9]{4}-?[0-9]{2}-?[0-9]{2})/', views.day_list, name ='day_list'),
    re_path(r'list/', views.list, name ='list'),
    re_path(r'create/(?P<pk>\d+)/',views.create, name = 'create'),
	re_path(r'', views.reserv_home, name ='Reservations/reservationHome.html'),
]

visitMaker/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.views.generic import RedirectView
from accounts.views import (login_view, register_view, logout_view, list_users)
from home.views import(contact_view)
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include ('home.urls')) ,
    url(r'^request_reservation/', include('requestReserv.urls')),
    url(r'^reservation_home/', include('reservHome.urls', 'reservations')),
   # url(r'^contact_us/', include('contactUs.urls')),
    url(r'^register/', register_view, name='register'),
    url(r'^contact_us', contact_view , name = 'contactUs.html'),
    url(r'^manage/', list_users, name ='Users/manage.html'),
    url(r'^accounts/', include('accounts.urls', 'accounts')),
    url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^report_generation/', include('Reports.urls')),
    url(r'^$', RedirectView.as_view(url='/home', permanent = True)),
]

reservHome/models.py
from django.db import models

#for setting creation date
#from django.db.utils import timezone

class Reservation(models.Model):

	#choose docent
	docent = models.CharField(max_length=60)

	#organization name
	name = models.CharField(max_length=60)

	#organization email
	email = models.EmailField()

	#number of people attending
	people_number = models.PositiveIntegerField()

	TIME_CHOICES = (
		(9, '9:00am-10:00am'),
		(10, '10:00am-11:00am'),
		(11, '11:00am-12:00pm'),
		(12, '12:00pm-1:00pm'),
		(13, '1:00pm-2:00pm'),
		(14, '2:00pm-3:00pm'),
		(15, '3:00pm-4:00pm'),
	)
	#displays hour long intervals to choose from
	tour_time = models.IntegerField(
		choices=TIME_CHOICES
	)

	#syntax:
	# 	'yyyy-mm-dd'
	# 	'mm/dd/yyyy'
	# 	'mm/dd/yy'
	#form using widget to select input
	tour_date = models.DateField()

	#not required
	Special_Accommodations = models.TextField(blank=True)

	#date request was made
	#used for tours
	#automatically set
	creation_date = models.DateField(auto_now_add=True, editable=False)

	def __str__(self):
		return u'%s_%s_%s' % (self.name, self.tour_date, self.tour_time)

home/views.py
from django.shortcuts import render
# Create your views here.

def index(request):
	return render (request, 'index.html',)

def contact_view(request):
  return render(request, 'contactUs.html',)

home/templates/Reservations/addReserv.html
{% load static %}
<html>
    {% include "univheader.html" %}
	<body class="background">
		<div class="header2">
			Fill out the reservation form with the tour information.
		</div>
		<!-- posts error on bad input -->
		{% if form.errors %}
        	<p style="color: red;">
            	Please correct the error{{ form.errors|pluralize }} below.
        	</p>
    	{% endif %}
    	<!-- uses form fields to request input -->
    	<form action="" method="post" novalidate>
        	<table>
            	{{ form.as_table }}
        	</table>
        	{% csrf_token %}
        	<input name="submit" type="submit" value="Submit">
    	</form>
	</body>
</html>

home/templates/Reservations/confirmReserv.html
{% load static %}
<html>
	{% include "univheader.html" %}

	{% block content %}
	<body class="background">
		<div class="header2">
			Your reservation has been added to the database.

			<a href= "{% url 'reservations:send_email' pk=entry.pk %}">Send Confirmation Email</a>
		</div>

		<table>
		<tbody>	
			<tr>
				<th>Name: </th>
			    <th> {{entry.name }} </th>
			</tr>
			<tr>
				<th>email: </th>
				<th> {{entry.email }} </th>	
			</tr>
			<tr>
				<th>Date: </th>
				<th> {{entry.tour_date}} </th>
			</tr>
			<tr>
				<th>Time: </th>
				<th> {{entry.get_tour_time_display}} </th>
			</tr>
			<tr>
				<th>Number Attending: </th>
				<th> {{entry.people_number}} </th>
			</tr>
			<tr>
				<th>Docent: </th>
				<th> {{entry.docent}} </th>
			</tr>
			<tr>
				<th>Special Accommodations: </th>
				<th> {{entry.Special_Accommodations}} </th>
			</tr>
		</tbody>
		</table>
		
		<div>
			<a href= "{% url 'reservations:edit' pk=entry.pk %}">Edit reservation.</a>
			<a href= "{% url 'reservations:delete' pk=entry.pk %}">Delete Reservation.</a>
		</div>
	</body>

	{% endblock %}
</html>

home/templates/Reservations/list.html
<html>
	{% include "univheader.html" %}
	<body class="background">
		<div class="text"><a href="{% url 'reservations:add_reservation' %}" class="btn btn-primary">
		          <span class="glyphicon glyphicon-pencil"></span> Create a new reservation
		</a></div>
		<h2>Existing Reservations</h2>
		{% include 'Reservations/list_reservations.html' %}
		<p style="font-size: 20px; text-align: right"><br> Click <a href= "/reservation_home/">here</a> to return to the reservation home page. </p>
	</body>
</html>

home/templates/Reservations/list_reservations.html
 <!-- jQuery -->
<script type="text/javascript" charset="utf8" src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.8.2.min.js"></script>
<!-- DataTables -->
<script type="text/javascript" charset="utf8" src="http://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/jquery.dataTables.min.js"></script>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/display_entries.css' %}">
{% if reservation_list %}
  <table id="display_entries" class="display_entries">
    <thead>
      <tr>
      	<th>Edit</th>
		<th>Date</th>
		<th>Time Slot</th>
		<th>Organization</th>
		<th>Number Attending</th>
		<th>Docent</th>
		<th>Special Accommodations</th>
		<th>Delete</th>
	</tr>
    </thead>
    <tbody>{% for entry in reservation_list %}
      <tr>
      	<td><a href="{% url 'reservations:edit' pk=entry.pk %}"><span class="glyphicon glyphicon-pencil"></span></a></td>
		<td>{{entry.tour_date}}</td>
		<td>{{entry.get_tour_time_display}}</td>
		<td>{{entry.name}}</td>
		<td>{{entry.people_number}}</td>
		<td>{{entry.docent}}</td>
		<td>{% if entry.Special_Accommodations %}<span class="glyphicon glyphicon-ok"></span>{% endif %}</td>
		<td><a href="{% url 'reservations:delete' pk=entry.pk %}"><span class="glyphicon glyphicon-trash"></span></a></td>
	  </tr>{% endfor %}
    </tbody>
  </table>
  <script>
  $(function(){
    $("#display_entries").dataTable();
  })
  </script>
{% else %}
	<p class="text"> <span style="color: #853b23; font-size: 20px;">No reservations.</span> </p>
{% endif %}

home/templates/Reservations/reservationHome.html
{% load static %}
{% load reservation_tags %}
<html>
	{% include "univheader.html" %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/display_entries.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/calendar.css' %}">
	<script src="{% static 'js/calendar.js' %}"></script>
	<body class="background">
		<div class="text">
			<a href="{% url 'reservations:add_reservation' %}" class="btn btn-primary">
				<span class="glyphicon glyphicon-pencil"></span> Create a new reservation </a>
			<a href="{% url 'requests:list' %}" class="btn btn-success">
				<span class="glyphicon glyphicon-exclamation-sign"></span> View requests </a>
			<a href="{% url 'reservations:list' %}" class="btn btn-info">
				<span class="glyphicon glyphicon-list-alt"></span> View all reservations </a>
		</div>
		<h2>Upcoming Reservations</h2>
		{% get_future_set reservation_list as future_set %}
		{% include 'Reservations/list_reservations.html' with reservation_list=future_set %}
		<p><br></p>

		<!-- Calendar Code -->
		<script>
			var dayList_url = "{% url 'reservations:day_list' '0000-11-22' %}";
		</script>
		<div class="calendar-wrapper">
  			<button id="btnPrev" type="button">Previous Month</button>
	  		<button id="btnNext" type="button">Next Month</button>
  			<div id="divCal"></div>
		</div>
		<p style="font-size: 20px; text-align: right;"> <br> Click <a href= "/home/">here</a> to return to the home page. </p>
	</body>
</html>