home/urls.py
from django.conf.urls import url
from home import views

urlpatterns = [
	url(r'^$', views.index, name ='index.html'),
]

requestReserv/urls.py
from django.conf.urls import re_path, include
from requestReserv import views

app_name = 'requests'

urlpatterns = [
  re_path(r'^$', views.request_new, name ='Requests/requestReserv.html'),
  re_path(r'list/', views.list, name ='list'),
  re_path(r'delete/(?P<pk>\d+)/', views.delete, name ='delete'),
  re_path(r'confirm_request/(?P<pk>\d+)/', views.request_conf, name ='confirmRequest'),
]

reservHome/urls.py
from django.conf.urls import re_path, include
from django.urls import path
from reservHome import views

app_name = 'reservations'

urlpatterns = [
	path('add_reservation/', views.reserv_new, name ='add_reservation'),
	# (route, view, kwargs=NONE, name=NONE)
    re_path(r'confirm_reservation/(?P<pk>\d+)/', views.reserv_conf, name ='confirm_reservation'),
    re_path(r'send_email/(?P<pk>\d+)/', views.send_email, name ='send_email'),
    re_path(r'edit/(?P<pk>\d+)/', views.reserv_edit, name ='edit'),
    re_path(r'delete/(?P<pk>\d+)/', views.reserv_delete, name ='delete'),
    re_path(r'day_list/(?P<date>[0-9]{4}-?[0-9]{2}-?[0-9]{2})/', views.day_list, name ='day_list'),
    re_path(r'list/', views.list, name ='list'),
    re_path(r'create/(?P<pk>\d+)/',views.create, name = 'create'),
	re_path(r'', views.reserv_home, name ='Reservations/reservationHome.html'),
]

visitMaker/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.views.generic import RedirectView
from accounts.views import (login_view, register_view, logout_view, list_users)
from home.views import(contact_view)
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include ('home.urls')) ,
    url(r'^request_reservation/', include('requestReserv.urls')),
    url(r'^reservation_home/', include('reservHome.urls', 'reservations')),
   # url(r'^contact_us/', include('contactUs.urls')),
    url(r'^register/', register_view, name='register'),
    url(r'^contact_us', contact_view , name = 'contactUs.html'),
    url(r'^manage/', list_users, name ='Users/manage.html'),
    url(r'^accounts/', include('accounts.urls', 'accounts')),
    url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^report_generation/', include('Reports.urls')),
    url(r'^$', RedirectView.as_view(url='/home', permanent = True)),
]

requestReserv/models.py
from django.db import models

# Create your models here.
class Request(models.Model):
	#organization name
	name = models.CharField(max_length=60)

	#organization email
	email = models.EmailField()

	#number of people visiting
	people_number = models.PositiveIntegerField()

	TIME_CHOICES = (
		(9, '9:00am-10:00am'),
		(10, '10:00am-11:00am'),
		(11, '11:00am-12:00pm'),
		(12, '12:00pm-1:00pm'),
		(13, '1:00pm-2:00pm'),
		(14, '2:00pm-3:00pm'),
		(15, '3:00pm-4:00pm'),
	)
	#displays hour long intervals to choose from
	tour_time = models.IntegerField(
		choices=TIME_CHOICES
	)

	#syntax:
	# 	'yyyy-mm-dd'
	# 	'mm/dd/yyyy'
	# 	'mm/dd/yy'
	#form using widget to select input
	tour_date = models.DateField()

	#not required
	Special_Accommodations = models.TextField(blank=True)

	def __str__(self):
		return u'%s_%s_%s' % (self.name, self.tour_date, self.tour_time)

requestReserv/forms.py
from django import forms
from django.forms import ModelForm, Textarea, SelectDateWidget
from .models import Request

# form completely dependent on base model : Request
class RequestForm(ModelForm):
	class Meta:
		model = Request
		fields = '__all__'
		widgets = {
			'tour_date': SelectDateWidget(),
			'Special_Accommodations': Textarea(),
		}

home/views.py
from django.shortcuts import render
# Create your views here.

def index(request):
	return render (request, 'index.html',)

def contact_view(request):
  return render(request, 'contactUs.html',)

requestReserv/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404

from django.contrib.auth.decorators import login_required
from django.conf import settings

from .models import Request
from .forms import RequestForm


#displays all requests
@login_required(login_url='/login/')
def list(request):
    request_list = Request.objects.all().order_by('tour_date', 'tour_time')
    return render(request, 'Requests/list.html', {'entries' : request_list})

# displays empty form to fill for new reservation
# must be valid to submit
# submit saves to database
def request_new(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = RequestForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            new_model=form.save(request.POST)
            new_model.save()
            # redirect to a new URL:
            return redirect('requests:confirmRequest', pk = new_model.pk)

    # if a GET (or any other method) we'll create a blank form
    else:
        form = RequestForm()
    return render(request, 'Requests/requestReserv.html', {'form': form})

# displays contents of just created request
def request_conf(request, pk):
  entry = get_object_or_404(Request, pk=pk)
  return render(request, 'Requests/confirmRequest.html', {'entry' : entry})

# allows user to delete selected model
@login_required(login_url='/login/')
def delete(request, pk):
    # grab and delete object
    entry = get_object_or_404(Request, pk=pk)
    entry.delete()
    # return HttpResponse('deleted')
    # proceed to reservatio home
    request_list = Request.objects.all()
    return render(request, 'Requests/list.html', {'entries' : request_list})

home/templates/Requests/confirmRequest.html
{% load static %}
<html>
	{% include "univheader.html" %}
	<body class="background">
		<div class="header2">
			Your request has been submitted.  If there are any changes, please <a href= "/contact_us/">contact us</a>.
		</div>

		<table>
		<tbody>	
			<tr>
				<th>Name:  </th>
			    <th> {{entry.name }} </th>
			</tr>
			<tr>
				<th>Email:  </th>
				<th> {{entry.email }} </th>	
			</tr>
			<tr>
				<th>Date:  </th>
				<th> {{entry.tour_date}} </th>
			</tr>
			<tr>
				<th>Time Slot:  </th>
				<th> {{entry.get_tour_time_display}} </th>
			</tr>
			<tr>
				<th>Number Attending:  </th>
				<th> {{entry.people_number}} </th>
			</tr>
			<tr>
				<th>Special Accommodations:  </th>
				<th> {{entry.Special_Accommodations}} </th>
			</tr>
		</tbody>
		</table>
		<div class = "add">
			Click <a href= "/home/">here</a> to return to the home page.
		</div>
	</body>

</html>

home/templates/Requests/list.html
{% load static %}
<html>
	{% include "univheader.html" %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/display_entries.css' %}">
	<body class="background">
		<h2>Existing Requests</h2>
		{% include 'Requests/list_requests.html' %}
		<p style="font-size: 20px; text-align: right"> <br> Click <a href= "/reservation_home/">here</a> to return to the reservation home page. </p>
	</body>
</html>

home/templates/Requests/list_requests.html
 <!-- jQuery -->
<script type="text/javascript" charset="utf8" src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.8.2.min.js"></script>
<!-- DataTables -->
<script type="text/javascript" charset="utf8" src="http://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/jquery.dataTables.min.js"></script>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/display_entries.css' %}">

{% if entries %}
  <table id="display_entries" class="display_entries">
    <thead>
      <tr>
      	<th>Create Reservation</th>
		<th>Date</th>
		<th>Time Slot</th>
		<th>Organization</th>
		<th>Number Attending</th>
		<th>Special Accommodations</th>
		<th>Delete</th>
	  </tr>
    </thead>
    <tbody>
    {% for entry in entries %}
      <tr>
      	<td><a href="{% url 'reservations:create' pk=entry.pk %}"><span class="glyphicon glyphicon-pencil"></span></a></td>
		<td>{{entry.tour_date}}</td>
		<td>{{entry.get_tour_time_display}}</td>
		<td>{{entry.name}}</td>
		<td>{{entry.people_number}}</td>
		<td>{% if entry.Special_Accommodations %}<span class="glyphicon glyphicon-ok"></span>{% endif %}</td>
		<td><a href="{% url 'requests:delete' pk=entry.pk %}"><span class="glyphicon glyphicon-trash"></span></a></td>
	  </tr>
	{% endfor %}
    </tbody>
  </table>
  <script>
  $(function(){
    $("#display_entries").dataTable();
  })
  </script>
{% else %}
	<p class="text"> <span style="color: #853b23; font-size: 20px;">No requests.</span> </p>
{% endif %}

home/templates/Requests/requestReserv.html
{% load static %}
<html>
	{% include "univheader.html" %}
	<body class="background">
		<div class="header2">
			Please fill out a reservation request form.
		</div>
		<!-- posts error on bad input -->
		{% if form.errors %}
        	<p style="color: red;">
            	Please correct the error{{ form.errors|pluralize }} below.
        	</p>
    	{% endif %}
    	<!-- uses form fields to request input -->
    	<form action="" method="post" novalidate>
        	<table>
            	{{ form.as_table }}
        	</table>
        	{% csrf_token %}
        	<input name="submit" type="submit" value="Submit">
    	</form>
	</body>
</html>